<?php

$currencies = [
    "euro" => [
        [
            "id" => "0",
            "title" => "10x €5 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "euro",
            "msName" => "euro5",
            "price" => "€ 14,95",
            "rating" => "4.1",
            "photos" => [
                "photo1" => "./assets/img/5_euro.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/5_euro_back.jpg",
                "photo4" => "./assets/img/5_euro_detail.jpg",
                "photo5" => "./assets/img/star-66.svg",
            ],
        ],
        [
            "id" => "1",
            "title" => "10x €10 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "euro",
            "msName" => "euro10",
            "price" => "€ 19,95",
            "rating" => "3.4",
            "photos" => [
                "photo1" => "./assets/img/10_euro.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/10_euro_back.jpg",
                "photo4" => "./assets/img/10_euro_detail.jpg",
                "photo5" => "./assets/img/star-33.svg",
            ],
        ],
        [
            "id" => "2",
            "title" => "10x €20 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "euro",
            "msName" => "euro20",
            "price" => "€ 29,95",
            "rating" => "4.2",
            "photos" => [
                "photo1" => "./assets/img/20_euro.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/20_euro_back.jpg",
                "photo4" => "./assets/img/20_euro_detail.jpg",
                "photo5" => "./assets/img/star-66.svg",
            ]
        ],
        [
            "id" => "3",
            "title" => "10x €50 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "euro",
            "msName" => "euro50",
            "price" => "€ 69,95",
            "rating" => "4.8",
            "photos" => [
                "photo1" => "./assets/img/50_euro.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/50_euro_back.jpg",
                "photo4" => "./assets/img/50_euro_detail.jpg",
                "photo5" => "./assets/img/star-100.svg",
            ],
        ],
        [
            "id" => "4",
            "title" => "10x €100 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "euro",
            "msName" => "euro100",
            "price" => "€ 149,95",
            "rating" => "4.6",
            "photos" => [
                "photo1" => "./assets/img/100_euro.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/100_euro_back.jpg",
                "photo4" => "./assets/img/100_euro_detail.jpg",
                "photo5" => "./assets/img/star-66.svg",
            ],
        ],
        [
            "id" => "5",
            "title" => "10x €200 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "euro",
            "msName" => "euro200",
            "price" => "€ 299,95",
            "rating" => "4.1",
            "photos" => [
                "photo1" => "./assets/img/200_euro.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/200_euro_back.jpg",
                "photo4" => "./assets/img/200_euro_detail.jpg",
                "photo5" => "./assets/img/star-66.svg",
            ],
        ],
        [
            "id" => "6",
            "title" => "10x €500 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "euro",
            "msName" => "euro500",
            "price" => "€ 899,95",
            "rating" => "3.0",
            "photos" => [
                "photo1" => "./assets/img/500_euro.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/500_euro_back.jpg",
                "photo4" => "./assets/img/500_euro_detail.jpg",
                "photo5" => "./assets/img/star-0.svg",
            ]
        ],
    ],
    "dollar" => [
        [
            "id" => "0",
            "title" => "10x $1 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "dollar",
            "msName" => "dollar1",
            "price" => "€ 7,95",
            "rating" => "3.5",
            "photos" => [
                "photo1" => "./assets/img/1_dollar.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/1_dollar_back.jpg",
                "photo4" => "./assets/img/1_dollar_detail.jpg",
                "photo5" => "./assets/img/star-33.svg",
            ],
        ],
        [
            "id" => "1",
            "title" => "10x $2 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "dollar",
            "msName" => "dollar2",
            "price" => "€ 9,95",
            "rating" => "4.0",
            "photos" => [
                "photo1" => "./assets/img/2_dollar.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/2_dollar_back.jpg",
                "photo4" => "./assets/img/2_dollar_detail.jpg",
                "photo5" => "./assets/img/star-66.svg",
            ],
        ],
        [
            "id" => "2",
            "title" => "10x $5 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "dollar",
            "msName" => "dollar5",
            "price" => "€ 39,95",
            "rating" => "4.0",
            "photos" => [
                "photo1" => "./assets/img/5_dollar.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/5_dollar_back.jpg",
                "photo4" => "./assets/img/5_dollar_detail.jpg",
                "photo5" => "./assets/img/star-66.svg",
            ],
        ],
        [
            "id" => "3",
            "title" => "10x $10 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "dollar",
            "msName" => "dollar10",
            "price" => "€ 69,95",
            "rating" => "5.0",
            "photos" => [
                "photo1" => "./assets/img/10_dollar.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/10_dollar_back.jpg",
                "photo4" => "./assets/img/10_dollar_detail.jpg",
                "photo5" => "./assets/img/star-100.svg",
            ],
        ],
        [
            "id" => "4",
            "title" => "10x $20 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "dollar",
            "msName" => "dollar20",
            "price" => "€ 149,95",
            "rating" => "4.0",
            "photos" => [
                "photo1" => "./assets/img/20_dollar.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/20_dollar_back.jpg",
                "photo4" => "./assets/img/20_dollar_detail.jpg",
                "photo5" => "./assets/img/star-66.svg",
            ],
        ],
        [
            "id" => "5",
            "title" => "10x $50 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "dollar",
            "msName" => "dollar50",
            "price" => "€ 349,95",
            "rating" => "5.0",
            "photos" => [
                "photo1" => "./assets/img/50_dollar.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/50_dollar_back.jpg",
                "photo4" => "./assets/img/50_dollar_detail.jpg",
                "photo5" => "./assets/img/star-100.svg",
            ],
        ],
        [
            "id" => "6",
            "title" => "10x $100 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "dollar",
            "msName" => "dollar100",
            "price" => "€ 849,95",
            "rating" => "4.5",
            "photos" => [
                "photo1" => "./assets/img/100_dollar.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/100_dollar_back.jpg",
                "photo4" => "./assets/img/100_dollar_detail.jpg",
                "photo5" => "./assets/img/star-66.svg",
            ]
        ],
    ],
    "yen" => [
        [
            "id" => "0",
            "title" => "10x ¥1000 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "yen",
            "msName" => "yen1000",
            "price" => "€ 34,95",
            "rating" => "5.0",
            "photos" => [
                "photo1" => "./assets/img/1000_yen.png",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/1000_yen_back.png",
                "photo4" => "./assets/img/1000_yen_detail.png",
                "photo5" => "./assets/img/star-100.svg",
            ],
        ],
        [
            "id" => "1",
            "title" => "10x ¥2000 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "yen",
            "msName" => "yen2000",
            "price" => "€ 89,95",
            "rating" => "3.6",
            "photos" => [
                "photo1" => "./assets/img/2000_yen.png",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/2000_yen_back.png",
                "photo4" => "./assets/img/2000_yen_detail.png",
                "photo5" => "./assets/img/star-33.svg",
            ],
        ],
        [
            "id" => "2",
            "title" => "10x ¥5000 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "yen",
            "msName" => "yen5000",
            "price" => "€ 179,95",
            "rating" => "4.8",
            "photos" => [
                "photo1" => "./assets/img/5000_yen.png",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/5000_yen_back.png",
                "photo4" => "./assets/img/5000_yen_detail.png",
                "photo5" => "./assets/img/star-100.svg",
            ],
        ],
        [
            "id" => "3",
            "title" => "10x ¥10000 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "yen",
            "msName" => "yen10000",
            "price" => "€ 399,95",
            "rating" => "3.3",
            "photos" => [
                "photo1" => "./assets/img/10000_yen.png",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/10000_yen_back.png",
                "photo4" => "./assets/img/10000_yen_detail.png",
                "photo5" => "./assets/img/star-33.svg",
            ]
        ],
    ],
    "pond" => [
        [
            "id" => "0",
            "title" => "10x £5 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "pond",
            "msName" => "pound5",
            "price" => "€ 34,95",
            "rating" => "3.6",
            "photos" => [
                "photo1" => "./assets/img/5_pounds.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/5_pounds_back.jpg",
                "photo4" => "./assets/img/5_pounds_detail.jpg",
                "photo5" => "./assets/img/star-33.svg",
            ],
        ],
        [
            "id" => "1",
            "title" => "10x £10 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "pond",
            "msName" => "pound10",
            "price" => "€ 59,95",
            "rating" => "4.1",
            "photos" => [
                "photo1" => "./assets/img/10_pounds.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/10_pounds_back.jpg",
                "photo4" => "./assets/img/10_pounds_detail.jpg",
                "photo5" => "./assets/img/star-66.svg",
            ],
        ],
        [
            "id" => "2",
            "title" => "10x £20 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "pond",
            "msName" => "pound20",
            "price" => "€ 149,95",
            "rating" => "3.9",
            "photos" => [
                "photo1" => "./assets/img/20_pounds.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/20_pounds_back.jpg",
                "photo4" => "./assets/img/20_pounds_detail.jpg",
                "photo5" => "./assets/img/star-33.svg",
            ],
        ],
        [
            "id" => "3",
            "title" => "10x £50 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "pond",
            "msName" => "pound50",
            "price" => "€ 449,95",
            "rating" => "3.3",
            "photos" => [
                "photo1" => "./assets/img/50_pounds.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/50_pounds_back.jpg",
                "photo4" => "./assets/img/50_pounds_detail.jpg",
                "photo5" => "./assets/img/star-33.svg",
            ]
        ],
    ],
    "roebel" => [
        [
            "id" => "0",
            "title" => "10x ₽100 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "roebel",
            "msName" => "roebel100",
            "price" => "€ 7,95",
            "rating" => "4.1",
            "photos" => [
                "photo1" => "./assets/img/100_roebel.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/100_roebel_back.jpg",
                "photo4" => "./assets/img/100_roebel_detail.jpg",
                "photo5" => "./assets/img/star-66.svg",
            ],
        ],
        [
            "id" => "1",
            "title" => "10x ₽200 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "roebel",
            "msName" => "roebel200",
            "price" => "€ 15,95",
            "rating" => "4.0",
            "photos" => [
                "photo1" => "./assets/img/200_roebel.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/200_roebel_back.jpg",
                "photo4" => "./assets/img/200_roebel_detail.jpg",
                "photo5" => "./assets/img/star-66.svg",
            ],
        ],
        [
            "id" => "2",
            "title" => "10x ₽1000 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "roebel",
            "msName" => "roebel1000",
            "price" => "€ 69,95",
            "rating" => "4.4",
            "photos" => [
                "photo1" => "./assets/img/1000_roebel.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/1000_roebel_back.jpg",
                "photo4" => "./assets/img/1000_roebel_detail.jpg",
                "photo5" => "./assets/img/star-66.svg",
            ],
        ],
        [
            "id" => "3",
            "title" => "10x ₽2000 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "roebel",
            "msName" => "roebel2000",
            "price" => "€ 159,95",
            "rating" => "3.3",
            "photos" => [
                "photo1" => "./assets/img/2000_roebel.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/2000_roebel_back.jpg",
                "photo4" => "./assets/img/2000_roebel_detail.jpg",
                "photo5" => "./assets/img/star-33.svg",
            ],
        ],
        [
            "id" => "4",
            "title" => "10x ₽5000 biljetten",
            "description" => "Alle echtheidskenmerken gegarandeert",
            "category" => "roebel",
            "msName" => "roebel5000",
            "price" => "€ 299,95",
            "rating" => "4.6",
            "photos" => [
                "photo1" => "./assets/img/5000_roebel.jpg",
                "photo2" => "./assets/img/cart.png",
                "photo3" => "./assets/img/5000_roebel_back.jpg",
                "photo4" => "./assets/img/5000_roebel_detail.jpg",
                "photo5" => "./assets/img/star-66.svg",
            ]
        ],
    ],
];

// foreach ($currencies["euro"] as $currency) {
//     // echo $currency["title"] . "<br>";

//     echo "<div class='product'>";
//     echo "<img src=" . "'" . ($currency["photos"]["photo1"]) . "'" . "  class='geld-briefje'/>";
//     echo "<span class='product-text'>";
//     echo $currency["title"];
//     echo "</span>";
//     echo "<div class='cart-button'>";
//     echo "<img class='cart-img'/>";
//     echo "</div>";
//     echo "<span class='beschrijving'>";
//     echo $currency["description"];
//     echo "</span>";
//     echo "<span class='prijs'>";
//     echo $currency["price"];
//     echo "</span>";
//     echo "</div>";

//     echo "--------------------------<br>";
// }

